# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/common" # Location of package manifests
    schedule:
      interval: "weekly"


# tools
  - package-ecosystem: "gomod"
    directory: "tools/bashreadline"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/bindsnoop"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/biolatency"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/biopattern"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/biosnoop"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/biostacks"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/biotop"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/bitesize"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/cachestat"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/capable"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/cpudist"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/cpufreq"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/drsnoop"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/execsnoop"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/exitsnoop"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/filelife"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/filetop"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/fsdist"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/fsslower"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/funclatency"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/gethostlatency"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/hardirqs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/javagc"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/klockstat"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/ksnoop"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/llcstat"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/mdflush"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/mountsnoop"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/numamove"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/offcputime"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/oomkill"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/opensnoop"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/readahead"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/runqlat"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/runqlen"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/runqslower"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/sigsnoop"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/slabratetop"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/softirqs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/solisten"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/statsnoop"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/syscount"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/tcpconnect"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/tcpconnlat"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/tcplife"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/tcprtt"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/tcpstates"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/tcpsynbl"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/tcptop"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/tcptracer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/vfsstat"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tools/wakeuptime"
    schedule:
      interval: "weekly"
